events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    # Ampliar el límite de carga por defecto de 1MB a 50MB para PDFs pesados
    client_max_body_size 50M;
    
    server {
        listen 8000;
        server_name localhost;
        
        # Sirve el HTML frontend por defecto
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ @api;
        }

        # Redirecciona endpoints no estáticos a FastAPI
        location @api {
            proxy_pass http://fastapi_app:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
